global:
  scrape_interval: "30s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"

  - job_name: "rails"
    static_configs:
      - targets:
        - "rails:9394"

  - job_name: "sidekiq"
    static_configs:
      - targets:
        - "sidekiq:9394"
  