version: '3.7'

services:
  loadbalance:
    image: nginx:1.13.1
    restart: always
    container_name: rails-loadbalance
    depends_on:
      - rails
    ports:
      - 2580:80
    expose:
      - 80
      - 443
    volumes:
      - ./app:/app
      - ./nginx:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      proxy:
      default:
        aliases:
          - railsnginx

  rails:
    image: maximmonin/rails
    container_name: rails
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      default:
        aliases:
          - rails
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
     - ./app:/app
#     - ./gems:/usr/local/bundle/gems
     - ./mail:/etc/ssmtp
     - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000

  sidekiq:
    image: maximmonin/rails
    container_name: rails-sidekiq
    restart: always
    depends_on:
      - mysql
      - redis
      - rails
    entrypoint:
      - bash
      - -c
      - |
        echo 'Starting sidekiq'
        /sidekiq-entrypoint.sh
    networks:
      default:
        aliases:
          - sidekiq
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
     - ./app:/app
#     - ./gems:/usr/local/bundle/gems
     - ./mail:/etc/ssmtp
     - /etc/localtime:/etc/localtime:ro

  mysql:
    image: mariadb:10.4.11
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /init/init.sql
    container_name: rails-mysql
    networks:
      default:
        aliases:
          - mysql
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/init/init.sql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:5.0.7
    container_name: rails-redis
    restart: always
    networks:
      default:
        aliases:
          - redis
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro

  selenium:
    image: selenium/hub
    restart: always
    container_name: rails-selenium
    depends_on:
      - loadbalance
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GRID_MAX_SESSION=5
      - GRID_BROWSER_TIMEOUT=30000 
    networks:
      default:
        aliases:
          - selenium

  selenium-chrome:
    image: selenium/node-chrome
    restart: always
    container_name: rails-selenium-chrome
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:

  selenium-firefox:
    image: selenium/node-firefox
    restart: always
    container_name: rails-selenium-firefox
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:

  phpadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rails-phpadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 2581:80
    networks:
      default:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
  proxy:
    external:
      name: nginx-proxy
