version: '3.7'

services:
  loadbalance:
    image: nginx:1.13.1
    restart: always
    container_name: rails-loadbalance
    depends_on:
      - rails
    ports:
      - 2580:80
    expose:
      - 80
      - 443
    volumes:
      - ./app:/app
      - ./cfg/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      proxy:
      default:

  rails:
    image: maximmonin/rails
    container_name: rails
    restart: always
    depends_on:
      - db
      - redis
    networks:
      default:
        aliases:
          - rails
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - PIDFILE=tmp/pids/dev.pid
      - EDITOR=mcedit
      - APP_DATABASE_PASSWORD=rails
      - VIRTUAL_HOST
    volumes:
     - ./app:/app
     - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000

  sidekiq:
    image: maximmonin/rails
    container_name: rails-sidekiq
    restart: always
    depends_on:
      - db
      - redis
      - rails
    entrypoint:
      - bash
      - -c
      - |
        echo 'Starting sidekiq'
        /sidekiq-entrypoint.sh
    networks:
      default:
        aliases:
          - sidekiq
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - RAILS_MAX_THREADS=5
      - APP_DATABASE_PASSWORD=rails
      - VIRTUAL_HOST
    volumes:
     - ./app:/app
     - /etc/localtime:/etc/localtime:ro

  db:
    image: postgres:12.3
    restart: always
    container_name: rails-db
    networks:
      default:
        aliases:
          - db
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./cfg/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6.0.7
    container_name: rails-redis
    restart: always
    networks:
      default:
        aliases:
          - redis
    volumes:
      - ./redis:/data
      - ./cfg/redis.conf:/redis.conf
      - /etc/localtime:/etc/localtime:ro
    command: [ "redis-server", "/redis.conf" ]

  #######################################################
  ## TESTING                                           ##
  #######################################################
  
  nginxtest:
    image: nginx:1.13.1
    restart: always
    container_name: rails-nginxtest
    depends_on:
      - railstest
    ports:
      - 2582:80
    expose:
      - 80
    volumes:
      - ./app:/app
      - ./cfg/nginxtest.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:

  railstest:
    image: maximmonin/rails
    container_name: rails-test
    restart: always
    depends_on:
      - db
      - redis
      - rails
    networks:
      default:
    environment:
      - RAILS_ENV=test
      - REDIS_URL=redis://redis:6379
      - RAILS_MAX_THREADS=5
      - PIDFILE=tmp/pids/test.pid
      - WEB_CONCURRENCY=1
      - VIRTUAL_HOST
    volumes:
     - ./app:/app
     - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000

  selenium:
    image: selenium/hub
    restart: always
    container_name: rails-selenium
    depends_on:
      -  nginxtest
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    environment:
      - GRID_MAX_SESSION=5
      - GRID_BROWSER_TIMEOUT=30000 
    networks:
      default:
        aliases:
          - selenium

  selenium-chrome:
    image: selenium/node-chrome
    restart: always
    container_name: rails-selenium-chrome
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    networks:
      default:

  selenium-firefox:
    image: selenium/node-firefox
    restart: always
    container_name: rails-selenium-firefox
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    networks:
      default:

  pgadmin:
    image: dpage/pgadmin4
    container_name: rails-pgadmin
    restart: always
    depends_on:
      - db
    ports:
      - 2581:80
    networks:
      default:
    volumes:
      - ./cfg/servers.json:/pgadmin4/servers.json
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
  proxy:
    external:
      name: nginx-proxy
