CREATE DATABASE IF NOT EXISTS rails_dev  CHARACTER SET UTF8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS rails_test CHARACTER SET UTF8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS rails_prod CHARACTER SET UTF8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'rails'@'localhost' IDENTIFIED BY 'rails';
GRANT ALL PRIVILEGES ON *.* TO 'rails'@'localhost';
CREATE USER IF NOT EXISTS rails IDENTIFIED BY 'rails';
GRANT ALL PRIVILEGES ON *.* TO 'rails'@'%';